name: React Components Package

on:
  push:
    branches:
      - actiontest
  pull_request:
    branches:
      - actiontest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Publish to GitHub Packages
      - run: npm config set registry https://npm.pkg.github.com/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      # Publish to npm registry
      - run: npm config set registry https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
